### ISSUE TITLE
Cast issue in unlinkDeviceToken()

### ISSUE THREAD

**Issue by AjinkyaTaranekar** [yellowmessenger/ymchat-flutter#4]
Hello, isn't this should be 
`bool unLinkDeviceTokenResult = await _channel.invokeMethod(`
as it's throwing error.

https://github.com/yellowmessenger/ymchat-flutter/blob/550d518a392c8961329053edeb9c29bb8ba985b6/lib/ymchat_flutter.dart#L68

Can you please, have a look at this one.

Regards,
Ajinkya Taranekar

**Comment by PurushYM** [comment]
This should be dynamic it will throw string errors also

`dynamic unLinkDeviceTokenResult`

Fixed
