### ISSUE TITLE
App not running on the web

### ISSUE THREAD

**Issue by Usmani7** [yellowmessenger/ymchat-flutter#55]
When we run app on the web after adding this package, it gives the following error, and the app gets terminated:

![image](https://user-images.githubusercontent.com/46865365/226269818-3ad8763e-65fa-4703-8915-2da7ee71d9a6.png)

**Comment by Coffiie** [comment]
Is there any update on this? This is a compile time error on Flutter web and it really restricts us since we're using Web, Android and iOS builds for our flutter project.

**Comment by Coffiie** [comment]
There seems to be an issue with Line 3 and Line 4, these are unused imports and we can simply remove them from the package.

I can create a PR if I am given rights. It's just removal of two lines.

@purushyb @sankalp211 @rohit-131 @sukrit-ym

**Comment by sukrit-ym** [comment]
Hi @Coffiie can you mention imports here that need to be removed?
@sankalp211 please check this.

**Comment by Coffiie** [comment]
Sure, they are these two. They are unused, so safe to remove.
`import 'dart:developer';`
`import 'dart:ffi';`

**Comment by sukrit-ym** [comment]
Thanks @Coffiie ..let me get this removed and tested. If everything works fine we will release a patch fix by Wednesday EOD.

**Comment by Coffiie** [comment]
Sounds good! Looking forward.

**Comment by sankalp211** [comment]
@Coffiie @Usmani7 

This is resolved in version [v2.7.1](https://github.com/yellowmessenger/ymchat-flutter/releases/tag/v2.7.1). Please update to the latest.

**Comment by Coffiie** [comment]
> @Coffiie @Usmani7
> 
> This is resolved in version [v2.7.1](https://github.com/yellowmessenger/ymchat-flutter/releases/tag/v2.7.1). Please update to the latest.

Thanks! It's working now <3
