### ISSUE TITLE
`com.yellowmessenger.ymchatexample.fileprovider` package name causing issue when working with different flavor.

### ISSUE THREAD

**Issue by bhavik-multipl** [yellowmessenger/ymchat-flutter#6]
adb: failed to install app.apk: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.yellowmessenger.ymchatexample.fileprovider (in package your.package.name.beta) is already used by your.package.name]

**Comment by PurushYM** [comment]
Looks like other application is already using this SDK with same provider name please change it by adding following to your android/app/src/main/res/values Strings.xml 

`<string name="application_id_for_provider">your.application.id.fileprovider</string>`

Note: if strings.xml is not present please create and add it

Example :
`<resources>
   ...
   ...
    <string name="application_id_for_provider">com.yellowmessenger.ymchatbotexample.fileprovider</string>
</resources>`

**Comment by bhavik-multipl** [comment]
Hey, Forget to update here. It worked, Thanks for the quick response.

**Comment by vinceluisrecto** [comment]
> Looks like other application is already using this SDK with same provider name, please change it by adding following code to your path `android/app/src/main/res/values Strings.xml `
> 
> ```
> <string name="application_id_for_provider">your.application.id.fileprovider</string>
> ```
> 
> Note: if strings.xml is not present please create and add it
> 
> Example :
> 
> ```
> <resources>
>      ...
>      ...
>     <string name="application_id_for_provider">com.yellowmessenger.ymchatbotexample.fileprovider</string>
> </resources>
> ```

I did add this code in Strings.xml but I still get the same results
